name: gseim-ci
on: [push, pull_request]
jobs:
  build-and-test:
    strategy:
      matrix:
        python-version: ['3.8'] # , '3.9']
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./gseim_grc/src/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Ubuntu and Python package dependencies
        run: |
          sudo apt install libgirepository1.0-dev libcairo2-dev pkg-config gir1.2-gtk-3.0 qtbase5-dev libxkbcommon-x11-0
          pip3 install pyqt5 poetry tox
      - name: Run Bazel test
        run: |
          tox -e py3-qt5
