name: gseim-ci
on: [push, pull_request]
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
    steps:
      - uses: actions/checkout@v3
      - name: Install Ubuntu and Python package dependencies
        run: |
          sudo apt install libgirepository1.0-dev libcairo2-dev pkg-config gir1.2-gtk-3.0 qtbase5-dev libxkbcommon-x11-0
          pip3 install pyqt5 tox build
        if: matrix.os == 'ubuntu-20.04'
      - name: Install Mac and Python dependencies
        run: |
          brew install pygobject3
          pip3 install pyqt5 tox build
        if: matrix.os == 'macos-11'
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.9.0
        with:
          package-dir: ./gseim_grc/
      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
